name: inspection_app
description: A cross-platform inspection record e-form app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.1
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
