name: Build Flutter App

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK (for Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Generate Platform Files
        run: flutter create . --platforms=windows,android

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App (.exe)
        run: flutter build windows --release

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: build/windows/runner/Release/

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
